image: Visual Studio 2022

environment:
  CODECOV_TOKEN:
    secure: efd83f5a-feff-4fec-844d-a7a3a7c339e5

build_script:
  - dotnet format Project/Midterm.sln --verify-no-changes

  - dotnet tool restore
  - dotnet cake

test_script:
  - dotnet test Project/Midterm.sln --no-build --collect:"XPlat Code Coverage"

after_test:
  - curl -Os https://uploader.codecov.io/latest/windows/codecov.exe
  - codecov.exe -f "**/coverage.cobertura.xml" -t %CODECOV_TOKEN%

on_failure:
  - echo "Build failed! AppVeyor will email you automatically."
